# Generated by Django 5.1.4 on 2025-01-11 14:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='appliance',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('users', models.IntegerField(default=0)),
                ('avg_consp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='generator',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=3)),
                ('activity_status', models.BooleanField(default=True)),
                ('current_production', models.IntegerField(default=0)),
                ('peak_capacity', models.IntegerField(default=0)),
                ('sections', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='grid',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('activity_status', models.BooleanField(default=True)),
                ('users', models.IntegerField(default=0)),
                ('load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('activity_status', models.BooleanField(default=True)),
                ('grids', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='bear',
            fields=[
                ('admin', models.IntegerField(default=0)),
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('current_usage', models.IntegerField(blank=True, default=0, null=True)),
                ('avg_usage', models.IntegerField(blank=True, default=0, null=True)),
                ('bill_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('pending', models.IntegerField(blank=True, default=0, null=True)),
                ('activity_status', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='bear_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='bear_user_permissions', to='auth.permission')),
                ('grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.grid')),
            ],
        ),
    ]
