# Generated by Django 5.1.4 on 2025-01-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
