# Generated by Django 5.1.4 on 2025-01-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grid',
            field=models.CharField(default='-1', max_length=50, null=True),
        ),
    ]
