# Generated by Django 5.1.4 on 2025-01-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bear_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_load',
            field=models.IntegerField(default=0),
        ),
    ]
