# Generated by Django 5.1.4 on 2025-01-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_section_max_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='sec1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='grid',
            name='sec2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='grid',
            name='sec3',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
