# Generated by Django 5.1.4 on 2025-01-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_activity_status_alter_user_avg_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appliance',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('useruid', models.CharField(max_length=100)),
                ('avg_consp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('useruid', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='generator',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=3)),
                ('activity_status', models.BooleanField(default=True)),
                ('curent_production', models.IntegerField(default=0)),
                ('peak_capcity', models.IntegerField(default=0)),
                ('grids', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='grid',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('activity_status', models.BooleanField(default=True)),
                ('users', models.IntegerField(default=0)),
                ('load', models.IntegerField(default=0)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('activity_status', models.BooleanField(default=True)),
                ('grids', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('load', models.IntegerField(default=0)),
                ('gen', models.CharField(max_length=50)),
            ],
        ),
    ]
