# Generated by Django 5.1.4 on 2025-01-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appliance_bill_generator_grid_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
