# Generated by Django 5.1.4 on 2025-01-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_generator_grid1_generator_grid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pending_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generator',
            name='grid1power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generator',
            name='grid2power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='grid',
            name='load',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='load',
            field=models.FloatField(default=0),
        ),
    ]
