# Generated by Django 5.1.4 on 2025-01-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bill_pending_amount_generator_grid1power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='current_production',
            field=models.FloatField(default=0),
        ),
    ]
