# Generated by Django 5.1.4 on 2025-01-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_generator_current_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='sections',
        ),
    ]
