# Generated by Django 5.1.4 on 2025-01-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_generator_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
