# Generated by Django 5.1.4 on 2025-01-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_generator_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bear',
            name='grid',
        ),
        migrations.AddField(
            model_name='bear',
            name='section',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
