# Generated by Django 5.1.4 on 2025-01-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_bear_grid_bear_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='bear',
            name='past_usage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='grids',
            field=models.CharField(max_length=50),
        ),
    ]
