# Generated by Django 5.1.4 on 2025-01-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_bear_past_usage_alter_section_grids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bear',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='bear',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='bear',
            name='user_permissions',
        ),
    ]
