# Generated by Django 5.1.4 on 2025-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_bear_groups_remove_bear_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
