# Generated by Django 5.1.4 on 2025-01-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bear',
            name='load',
            field=models.IntegerField(default=0),
        ),
    ]
