# Generated by Django 5.1.4 on 2025-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_schedule_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='serves',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gen_id', models.CharField(max_length=50)),
                ('grid_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='generator',
            name='grid1',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='grid1power',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='grid2',
        ),
        migrations.RemoveField(
            model_name='generator',
            name='grid2power',
        ),
        migrations.AddField(
            model_name='generator',
            name='canserve',
            field=models.IntegerField(default=0),
        ),
    ]
