# Generated by Django 5.1.4 on 2025-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_serves_remove_generator_grid1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serves',
            name='power_usage',
            field=models.FloatField(default=0.0),
        ),
    ]
