# Generated by Django 5.1.4 on 2025-02-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_serves_power_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='efficiency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generator',
            name='emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generator',
            name='fuel_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generator',
            name='generator_type',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='generator',
            name='overall_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generator',
            name='power_output',
            field=models.FloatField(default=0.0),
        ),
    ]
