# Generated by Django 5.1.4 on 2025-02-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_generator_efficiency_generator_emissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='fuel',
            field=models.CharField(max_length=30),
        ),
    ]
