# Generated by Django 5.1.4 on 2025-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_generator_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='generator_type',
            field=models.CharField(max_length=20),
        ),
    ]
