# Generated by Django 5.1.4 on 2025-02-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_generator_power_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bear',
            old_name='section',
            new_name='section_id',
        ),
    ]
